[package]
name = "alexandria"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
reqwest = {version = "0.12.4", features= ["json"] }
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
base64 = "0.22.1"
